name: 03 - Multiple job with condition example

on:
    push:
        branches: ["*"]

jobs:
    run-always-job:
        runs-on: ubuntu-latest
        steps:
            - name: run a single command
              run: echo "Welcome to GHA Classes"
            - name: run multiple commands in a step
              run: |
                echo "hello from Avinash"
                echo "You are learning GHA"

    run-on-test-branch-job:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/test'
        steps:
            - name: run a single command
              run: echo "THis is from second job"
